# This workflow will run npm checks.

name: NPM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Run linter
        run: yarn lint

      - name: Build outputs
        run: yarn build

      - name: Run tests
        run: yarn test
